config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root to: "events#index"
  get 'events/search'
  resources :users, only: [:show]
  resources :events, only: [:index, :new, :create, :show]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '荒川区' },
    { id: 2, name: '足立区' },
    { id: 3, name: '板橋区' },
    { id: 4, name: '江戸川区' },
    { id: 5, name: '大田区' },
    { id: 6, name: '葛飾区' },
    { id: 7, name: '北区' },
    { id: 8, name: '江東区' },
    { id: 9, name: '新宿区' },
    { id: 10, name: '品川区' },
    { id: 11, name: '渋谷区' },
    { id: 12, name: '墨田区' },
    { id: 13, name: '杉並区' },
    { id: 14, name: '世田谷区' },
    { id: 15, name: '台東区' },
    { id: 16, name: '千代田区' },
    { id: 17, name: '中央区' },
    { id: 18, name: '豊島区' },
    { id: 19, name: '中野区' },
    { id: 20, name: '練馬区' },
    { id: 21, name: '文京区' },
    { id: 22, name: '港区' },
    { id: 23, name: '目黒区' }
  ]

  include ActiveHash::Associations
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
  belongs_to_active_hash :genre

  validates :title, :price, :genre_id, :area_id, :address, :event_date, :opening_time, :start_time, :end_time, presence: true
  validates :price, numericality: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }

  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '音楽' },
    { id: 2, name: '演劇' },
    { id: 3, name: 'お笑い' },
    { id: 4, name: 'スポーツ' },
    { id: 5, name: 'クラシック' },
    { id: 6, name: 'アート' }
  ]

  include ActiveHash::Associations
  has_many :events
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,             presence: true
  validates :password,         format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'には英字と数字の両方を含めて設定してください' }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event

  def liked_by?(event_id)
    likes.where(event_id: event_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'test@test.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'ゲスト'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :search_event, only: [:index, :search]

  def index
    @events = Event.includes(:user).order('created_at DESC').limit(4)
    @ranks = Event.find(Like.group(:event_id).order('count(event_id) DESC').limit(4).pluck(:event_id))
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def search
    @results = @a.result(distinct: true).page(params[:page]).per(8).order('created_at DESC')
    p @results
  end

  private

  def event_params
    params.require(:event).permit(:image, :title, :price, :address, :event_date, :opening_time, :start_time, :end_time,
                                  :ticket_reservation, :info, :area_id, :genre_id).merge(user_id: current_user.id)
  end

  def search_event
    @a = Event.ransack(params[:q])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :event_params

  def create
    Like.create(user_id: current_user.id, event_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, event_id: params[:id]).destroy
  end

  private

  def event_params
    @event = Event.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end

  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<% @events.each do |event| %>
  <div class="card-group col-md-6 col-lg-3 effect-fade" style="width: 20rem;" >
    <%= link_to event_path(event.id), class: "event-link" do%>
    <div class="card new-event">
      <span class="event-info"><i class="fas fa-clock"></i> <%= event.created_at.strftime("%m月%d日%H時") %></span>
      <% if event.image.present? %>
        <%= image_tag event.image, class: 'card-img-top' %>
      <% else %>
        <%= image_tag "/assets/default-image.jpg", class: 'card-img-top' %>
      <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
        </div>
        <ul class="list-group">
          <li class="list-group-item">ジャンル　<%= event.genre.name %></li>
          <li class="list-group-item">会場　　　<%= event.area.name %></li>
          <li class="list-group-item">開催日　　<%= event.event_date.strftime("%Y年%-m月%-d日") %></li>
          <li class=" list-group-item like-button"><i class="fas fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= event.likes.count %></span></li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/_ranking.html.erb
<% @ranks.each.with_index(1) do |event, i| %>
  <div class="card-group col-md-6 col-lg-3 effect-fade" style="width: 20rem;" >
    <%= link_to event_path(event.id), class: "event-link" do%>
    <div class="card new-event">
      <span class="event-info"><i class="fas fa-clock"></i> <%= event.created_at.strftime("%m月%d日%H時") %></span>
      <% if event.image.present? %>
        <%= image_tag event.image, class: 'card-img-top' %>
      <% else %>
        <%= image_tag "/assets/default-image.jpg", class: 'card-img-top' %>
      <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
        </div>
        <ul class="list-group">
          <li class="list-group-item">ジャンル　<%= event.genre.name %></li>
          <li class="list-group-item">会場　　　<%= event.area.name %></li>
          <li class="list-group-item">開催日　　<%= event.event_date.strftime("%Y年%-m月%-d日") %></li>
          <li class="list-group-item like-button"><i class="fas fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= event.likes.count %></span></li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="container-fluid title-contents">
  <div class="top-page-image">
    <h2 class="image-title">LIVE SEARCH</h2>
    <p>都内のイベントを投稿、検索できるサービスです</p>
  </div>
</div>

<div class="container">
  <h5 class="event-title"><i class="fas fa-search fa-2x"></i>　イベントを探す</h5>
  <%= render "layouts/search" %>
</div>

<div class="container">
  <h5 class="event-title"><i class="far fa-newspaper fa-2x"></i>　新着イベント</h5>
    <div class="row">
      <%= render "events/event"  %>
    </div>
</div>

<div class="container">
  <h5 class="event-title"><i class="fas fa-crown fa-2x"></i>　人気イベント</h5>
    <div class="row">
      <%= render "events/ranking" %>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-sm-2 col-sm-8 offset-sm-2">
      <%= form_with model: @event, local: true do |f| %>

        <h5 class='form-header-text text-center'>
          <i class="fas fa-pen fa-2x"></i>　新規イベント投稿
        </h5>

        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
          <%= f.label :image, '画像' %>
          <%= f.file_field :image, class: 'form-control-file' %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :title, 'イベント名' %>
          <%= f.text_field :title, placeholder: 'イベント名を入力してください', class: 'form-control', autofocus: true %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :price, '金額' %>
          <%= f.text_field :price, class:"price-input", placeholder:'金額を入力してください', class: 'form-control' %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :area, '地域' %>
          <%= f.collection_select(:area_id, Area.all, :id, :name, {include_blank: "---"}, {class:"custom-select", id:"area"}) %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :genre, 'ジャンル' %>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "---"}, {class:"custom-select", id:"genre"}) %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :address, '会場' %>
          <%= f.text_field :address, placeholder: 'イベント会場を入力してください', class: 'form-control' %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :event_date, '開催日' %>
          <%= f.date_field :event_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :opening_time, '開場時間' %>
          <%= f.time_field :opening_time, class: 'form-control' %>
        </div>

        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :start_time, '開演時間' %>
          <%= f.time_field :start_time, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <span class="badge badge-danger">必須</span>
          <%= f.label :end_time, '終演時間' %>
          <%= f.time_field :end_time, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :ticket_reservation, 'チケット購入先' %>
          <%= f.url_field :ticket_reservation, placeholder: 'URLを入力してください', class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :info, '詳細' %>
          <%= f.text_field :info, placeholder: 'イベント詳細を入力してください', class: 'form-control' %>
        </div>


        <div class="submit-content text-center">
          <%= f.submit "投稿する" ,class: 'btn submit-btn' %>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<div class="container">
  <h5 class="event-title">検索結果一覧</h5>
  <div class="row">
    <% if @results.length !=0 %>
      <% @results.each do |result| %>
        <div class="card-group col-md-6 col-lg-3 effect-fade" style="width: 20rem;" >
          <%= link_to event_path(result.id), class: "event-link" do%>
            <div class="card new-event">
              <span class="event-info"><i class="fas fa-clock"></i> <%= result.created_at.strftime("%m月%d日%H時") %></span>
              <% if result.image.present? %>
                <%= image_tag result.image, class: 'card-img-top' %>
              <% else %>
                <%= image_tag "/assets/default-image.jpg", class: 'card-img-top' %>
              <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= result.title %></h5>
                </div>
                <ul class="list-group">
                  <li class="list-group-item">ジャンル　<%= result.genre.name %></li>
                  <li class="list-group-item">会場　　　<%= result.area.name %></li>
                  <li class="list-group-item">開催日　　<%= result.event_date.strftime("%Y年%-m月%-d日") %></li>
                  <li class=" list-group-item like-button"><i class="fas fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= result.likes.count %></span></li>
                </ul>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <h5 class="alert">該当する投稿はありません！</h5>
    <% end %>
  </div>
</div>

<div class="container text-center">
  <p class="paginate">
    <%= paginate @results %>
    <%= link_to 'トップページへ戻る', root_path %>
  </p>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h5 class='form-header-text text-center'>
        <%= @event.title %>
      </h5>
      <div>
        <% if @event.image.present? %>
          <%= image_tag @event.image, class: 'img-fluid rounded mx-auto d-block' %>
        <% else %>
          <%= image_tag "/assets/default-image.jpg", class: 'image-fulid rounded mx-auto d-block' %>
        <% end %>
      </div>
      <div class="table-responsive-lg text-center">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <th class="align-middle w-25">投稿者</th>
              <td class="align-middle"><%= @event.user.name %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">ジャンル</th>
              <td class="align-middle"><%= @event.genre.name %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">地域</th>
              <td class="align-middle"><%= @event.area.name %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">場所</th>
              <td class="align-middle"><%= @event.address %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">開催日</th>
              <td class="align-middle"><%= @event.event_date.strftime("%Y年%-m月%-d日") %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">開場</th>
              <td class="align-middle"><%= @event.opening_time.strftime("%-H時%-M分") %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">開演</th>
              <td class="align-middle"><%= @event.start_time.strftime("%-H時%-M分") %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">終演</th>
              <td class="align-middle"><%= @event.end_time.strftime("%-H時%-M分") %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">チケット購入先</th>
              <td class="align-middle"><%= @event.ticket_reservation %></td>
            </tr>
            <tr>
              <th class="align-middle w-25">詳細</th>
              <td class="align-middle"><%= @event.info %></td>
            </tr>
          </tbody>
        </table>
          <% if user_signed_in? %>
            <div id="likes_buttons<%= @event.id %>">
              <%= render partial: "likes/like", locals: { event:@event } %>
            </div>
          <% end %>
      </div>
        <%= link_to 'トップページにもどる', root_path,class: 'back-btn' %>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>©️Live Search</p>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-image: linear-gradient(-135deg, #83a4d4, #b6fbff);">
      <div class="header-logo">
        <%= link_to image_tag('logo.png', style: "width: 290px"), root_path %>
      </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNav">

      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><%= link_to '投稿一覧', root_path %></li>
            <li class="nav-item"><%= link_to '投稿する', new_event_path %></li>
            <li class="nav-item"><%= link_to 'マイページ', user_path(current_user.id) %></li>
            <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><%= link_to '投稿一覧', root_path %></li>
            <li class="nav-item"><%= link_to '新規登録', new_user_registration_path %></li>
            <li class="nav-item"><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
            <li class="nav-item"><%= link_to 'ログイン', new_user_session_path %></li>
          </ul>
        </div>
      <% end %>
      </div>
    </nav>
  </div>  
</header> 

app/views/layouts/_search.html.erb
<%= search_form_for @a, url: events_search_path do |f| %>
  <div class="search-wrapper">
    <div class="search-content">
        <%= f.label :title_or_info_cont, 'キーワード検索', class: 'label' %>
        <%= f.search_field :title_or_info_cont, placeholder: 'キーワードを入力', class:"search-form-control float-right" %>
    </div>
    <div class="search-content">
        <%= f.label :event_date_eq, '日付検索', class: 'label' %>
        <%= f.date_field :event_date_eq, class:"search-form-control float-right" %>
    </div>
    <div class="search-content">
        <%= f.label :genre_id_eq, 'ジャンルを選択', class: 'label' %>
        <%= f.collection_select(:genre_id_eq, Genre.all, :id, :name, {include_blank: "---"}, {class:"search-select-box float-right"}) %>
    </div>
    <div class="search-content">
        <%= f.label :area_id_eq, '地域を選択', class: 'label' %>
        <%= f.collection_select(:area_id_eq, Area.all, :id, :name, {include_blank: "---"}, {class:"search-select-box float-right"}) %>
    </div>
    <div class="search-content text-center">
      <%= f.submit 'この条件で検索する', class:"btn search-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "layouts/header" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="likes_buttons">
<% if user_signed_in? %>
  <% if current_user.liked_by?(@event.id) %>
    <%= link_to destroy_like_path(@event.id, current_user.likes.find_by(event_id: @event.id).id), method: :delete, remote: true do %>
      <p class="like-button"><i class="fas fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= @event.likes.count %></span></p>
    <% end %>
  <% else %>
    <%= link_to create_like_path(@event.id), method: :post, remote: true do %>
      <p class="like-button"><i class="far fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= @event.likes.count %></span></p>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/likes/create.js.erb
$('.likes_buttons').html("<%= j(render partial: 'likes/like', locals: {event: @event}) %>");

app/views/likes/destroy.js.erb
$('.likes_buttons').html("<%= j(render partial: 'likes/like', locals: {event: @event}) %>");

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="event-title"><i class="fas fa-user fa-2x"></i>　ユーザー情報</h5>
      <div class="table-responsive-lg text-center">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <td class="align-middle w-25">お名前</th>
              <td class="align-middle"><%= @user.name %></td>
            </tr>
              <td class="align-middle w-25">MAIL</th>
              <td class="align-middle"><%= @user.email %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h5 class="event-title"><i class="fas fa-heart fa-2x"></i>　<%= @user.name %>さんのお気に入りイベント</h5>
    <div class="row">
      <% @user.liked_events.each do |event| %>
        <div class="card-group col-md-6 col-lg-3 effect-fade" style="width: 20rem;" >
        <%= link_to event_path(event.id), class: "event-link" do%>
          <div class="card new-event">
            <span class="event-info"><i class="fas fa-clock"></i> <%= event.created_at.strftime("%m月%d日%H時") %></span>
            <% if event.image.present? %>
              <%= image_tag event.image, class: 'card-img-top' %>
            <% else %>
              <%= image_tag "/assets/default-image.jpg", class: 'card-img-top' %>
            <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
              </div>
              <ul class="list-group">
                <li class="list-group-item">ジャンル　<%= event.genre.name %></li>
                <li class="list-group-item">会場　　　<%= event.area.name %></li>
                <li class="list-group-item">開催日　　<%= event.event_date.strftime("%Y年%-m月%-d日") %></li>
                <li class=" list-group-item like-button"><i class="fas fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= event.likes.count %></span></li>
              </ul>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
</div>

<div class="container">
  <h5 class="event-title"><i class="far fa-newspaper fa-2x" style="color:lightskyblue"></i>　<%= @user.name %>さんの投稿イベント</h5>
  <div class="row">
    <% @user.events.each do |event| %>
      <div class="card-group col-md-6 col-lg-3 effect-fade" style="width: 20rem;" >
        <%= link_to event_path(event.id), class: "event-link" do%>
          <div class="card new-event">
            <span class="event-info"><i class="fas fa-clock"></i> <%= event.created_at.strftime("%m月%d日%H時") %></span>
            <% if event.image.present? %>
              <%= image_tag event.image, class: 'card-img-top' %>
            <% else %>
              <%= image_tag "/assets/default-image.jpg", class: 'card-img-top' %>
            <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
              </div>
              <ul class="list-group">
                <li class="list-group-item">ジャンル　<%= event.genre.name %></li>
                <li class="list-group-item">会場　　　<%= event.area.name %></li>
                <li class="list-group-item">開催日　　<%= event.event_date.strftime("%Y年%-m月%-d日") %></li>
                <li class=" list-group-item like-button"><i class="fas fa-heart fa-2x" style="color: #e82a2a;"></i><span style="color: #e82a2a"><%= event.likes.count %></span></li>
              </ul>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>